services:
  dochub:
    image: backend-dochub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - /server/.env
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=yash
      - POSTGRES_PASSWORD=yash
    volumes:
      - postgres-volume:/var/lib/postgresql/data
volumes:
  postgres-volume:
