services:
  dochub:
    image: backend-dochub
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=yash
      - POSTGRES_PASSWORD=yash
    volumes:
      - postgres-volume:/var/lib/postgresql/data
volumes:
  postgres-volume:
